---
az-configuration: (( availability_zones ))
iaas-configurations:
- additional_cloud_properties: {}
  bosh_disk_path: (( bosh_disk_path ))
  bosh_template_folder: (( bosh_template_folder ))
  bosh_vm_folder: (( bosh_vm_folder ))
  datacenter: (( vcenter_datacenter ))
  disk_type: (( disk_type ))
  enable_human_readable_name: false
  ensure_no_ip_conflicts: true
  ephemeral_datastore_clusters_string: ""
  ephemeral_datastores_string: (( vcenter_datastore ))
  name: default
  nsx_address: (( nsx_address ))
  nsx_ca_certificate: (( nsx_ca_certificate))
  nsx_mode: nsx-t
  nsx_networking_enabled: true
  nsx_password: (( nsx_credentials.password ))
  nsx_t_auth_type: local_user
  nsx_t_tag_nsx_vm_objects: false
  nsx_t_use_policy_api: true
  nsx_t_use_policy_api_migration_mode: false
  nsx_username: (( nsx_credentials.username ))
  persistent_datastore_clusters_string: ""
  persistent_datastores_string: (( vcenter_datastore ))
  ssl_verification_enabled: false
  vcenter_host: (( vcenter_server ))
  vcenter_password: (( vcenter_credentials.password ))
  vcenter_username: (( vcenter_credentials.username ))
network-assignment:
  network:
    name: ((management_network_name))
  other_availability_zones: []
  singleton_availability_zone:
    name: ((availability_zones.0.name))
networks-configuration:
  icmp_checks_enabled: false
  networks: ((network_configuration.networks))
properties-configuration:
  director_configuration:
    ntp_servers_string: ((ntp_servers_string))
  security_configuration:
    clear_default_trusted_certificates_store: false
    opsmanager_root_ca_trusted_certs: true
    generate_vm_passwords: true
