---
pivnet-product-slug: pivotal-container-service

file-glob: "pivotal-container-service*.pivotal"
product-version: ((pks-version))
stemcell-iaas: vsphere
stemcell-version: "1.506"

pivnet-api-token: ((pivnet_token))
