---
pivnet-product-slug: p-isolation-segment
file-glob: "p-isolation-segment-*.pivotal"
product-version: ((isolation-segment-version))

s3-access-key-id: ((s3_access_key_id))
s3-secret-access-key: ((s3_secret_access_key))
s3-bucket: ((s3_pivnet_products_bucket))
s3-region-name: us-east-1
s3-endpoint: ((s3_endpoint))
