---
pivnet-product-slug: ops-manager

file-glob: "ops-manager-vsphere*.ova"
product-version: ((opsman-version))

s3-access-key-id: ((s3_access_key_id))
s3-secret-access-key: ((s3_secret_access_key))
s3-bucket: ((s3_pivnet_products_bucket))
# code_snippet download-ops-manager-from-pivnet-usage end
