---
product-name: p-healthwatch2
network-properties:
  network:
    name: tas
  other_availability_zones:
  - name: ((availability_zones.0.name))
  singleton_availability_zone:
    name: ((availability_zones.0.name))
product-properties:
  .properties.enable_basic_auth:
    selected_option: enabled
    value: enabled
  .properties.grafana_route:
    selected_option: tas
    value: tas
resource-config:
  tsdb:
    persistent_disk:
      name: "102400"
      size_mb: "102400"