---
product-name: p-healthwatch2-pks-exporter
network-properties:
  network:
    name: tas
  service_network:
    name: tas
  other_availability_zones:
  - name: ((availability_zones.0.name))
  singleton_availability_zone:
    name: ((availability_zones.0.name))
product-properties:
  .bosh-health-exporter.health_check_az:
    value: ((availability_zones.0.name))
