---
product-name: p-healthwatch2-pks-exporter
network-properties:
  network:
    name: tas
  service_network:
    name: tas
  other_availability_zones:
  - name: ((availability_zones.0.name))
  singleton_availability_zone:
    name: ((availability_zones.0.name))
product-properties:
  .bosh-health-exporter.health_check_az:
    value: ((availability_zones.0.name))
resource-config:
  bosh-health-exporter:
    max_in_flight: 2
    additional_networks: []
    additional_vm_extensions: []
    avi:
      pools: []
    instance_type:
      id: automatic
    instances: 0
    nsxt:
      lb:
        server_pools: []
      ns_groups: []
      vif_type: null
    persistent_disk:
      name: automatic
      size_mb: automatic
    swap_as_percent_of_memory_size: automatic