product-name: p-isolation-segment-iso-bank
product-properties:
  .isolated_router_iso_bank.disable_insecure_cookies:
    value: false
  .isolated_router_iso_bank.drain_timeout:
    value: 900
  .isolated_router_iso_bank.drain_wait:
    value: 20
  .isolated_router_iso_bank.enable_nontls_health_checks:
    value: true
  .isolated_router_iso_bank.enable_w3c:
    value: false
  .isolated_router_iso_bank.enable_write_access_logs:
    value: true
  .isolated_router_iso_bank.enable_zipkin:
    value: true
  .isolated_router_iso_bank.lb_healthy_threshold:
    value: 20
  .isolated_router_iso_bank.max_header_kb:
    value: 48
  .isolated_router_iso_bank.request_timeout_in_seconds:
    value: 900
  .isolated_router_iso_bank.static_ips:
    value: ((bank_isolation_segment_gorouter_static_ips))
  .properties.app_graceful_shutdown_period_in_seconds:
    value: 10
  .properties.app_log_rate_limiting:
    selected_option: disable
    value: disable
  .properties.compute_isolation:
    selected_option: ((bank_isolation_segment_compute_isolation))
    value: ((bank_isolation_segment_compute_isolation))
  .properties.compute_isolation.enabled.isolation_segment_name:
    value: ((bank_isolation_segment_name))
  .properties.container_networking:
    selected_option: enable
    value: enable
  .properties.enable_cpu_throttling:
    value: false
  .properties.enable_garden_containerd_mode:
    value: true
  .properties.enable_silk_policy_enforcement:
    value: false
  .properties.enable_smb_volume_driver:
    value: true
  .properties.enable_smb_volume_driver_force_nodfs:
    value: false
  .properties.enable_smb_volume_driver_force_noserverino:
    value: false
  .properties.garden_disk_cleanup:
    selected_option: reserved
    value: reserved
  .properties.garden_disk_cleanup.reserved.reserved_space_for_other_jobs_in_mb:
    value: 15360
  .properties.gorouter_customize_metrics_reporting:
    selected_option: disable
    value: disable
  .properties.gorouter_ssl_ciphers:
    value: ECDHE-RSA-AES128-GCM-SHA256:TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
  .properties.isolation_segment_domain:
    value: apps.((bank_isolation_segment_domain))
  .properties.networking_poe_ssl_certs:
    value: 
    - certificate:
        cert_pem: ((iso_segment_gorouter_ssl_cert))
        private_key_pem: ((iso_segment_gorouter_ssl_key))
      name: "gorouter"  
  .properties.networking_point_of_entry:
    selected_option: terminate_at_router
    value: terminate_at_router
  .properties.nfs_volume_driver:
    selected_option: enable
    value: enable
  .properties.policy_enforcement_poll_interval:
    value: 5
  .properties.route_integrity:
    selected_option: tls_verify
    value: tls_verify
  .properties.route_services_internal_lookup:
    value: false
  .properties.route_services_internal_server_port:
    value: 7070
  .properties.router_backend_max_conn:
    value: 500
  .properties.router_balancing_algorithm:
    selected_option: round_robin
    value: round-robin
  .properties.router_balancing_algorithm_az_preference:
    selected_option: none
    value: none
  .properties.router_client_cert_validation:
    selected_option: request
    value: request
  .properties.router_enable_proxy:
    value: false
  .properties.router_keepalive_connections:
    selected_option: enable
    value: enable
  .properties.router_only_trust_client_ca_certs:
    selected_option: disable
    value: disable
  .properties.router_redact_query_parameters:
    selected_option: none
    value: none
  .properties.router_sticky_session_cookie_names:
    value:
    - name: JSESSIONID
  .properties.router_sticky_sessions_for_auth_negotiate:
    value: true
  .properties.routing_disable_http:
    value: false
  .properties.routing_log_client_ips:
    selected_option: log_client_ips
    value: log_client_ips
  .properties.routing_table_sharding_mode:
    selected_option: ((bank_isolation_segment_routing_table_sharding_mode))
    value: ((bank_isolation_segment_routing_table_sharding_mode))
  .properties.routing_tls_termination:
    selected_option: load_balancer
    value: load_balancer
  .properties.routing_tls_version_range:
    selected_option: tls_v1_2_v1_3
    value: tls_v1_2_v1_3
  .properties.smoke_tests_isolation:
    selected_option: specified
    value: specified
  .properties.smoke_tests_isolation.specified.apps_domain:
    value: apps.172.30.7.70.nip.io
  .properties.smoke_tests_isolation.specified.org_name:
    value: org_a
  .properties.smoke_tests_isolation.specified.space_name:
    value: smoke-tests
  .properties.system_logging:
    selected_option: disabled
    value: disabled
network-properties:
  network:
    name: ((bank_isolation_segment_network_name))
  other_availability_zones:
    - name: ((availability_zones.0.name))
  singleton_availability_zone:
    name: ((availability_zones.0.name))
resource-config:
  isolated_diego_cell_iso_bank:
    max_in_flight: 4%
    additional_networks: []
    additional_vm_extensions: []
    avi:
      pools: []
    instance_type:
      id: automatic
    instances: 1
    nsxt:
      lb:
        server_pools: []
      ns_groups: []
      vif_type: null
    swap_as_percent_of_memory_size: automatic
  isolated_router_iso_bank:
    max_in_flight: 1
    additional_networks: []
    additional_vm_extensions: []
    avi:
      pools: []
    instance_type:
      id: automatic
    instances: 1
    nsxt:
      lb:
        server_pools: []
      ns_groups: []
      vif_type: null
    swap_as_percent_of_memory_size: automatic
errand-config:
  smoke_tests_isolation:
    post-deploy-state: true
