product-name: p-isolation-segment
product-properties:
  .isolated_router.disable_insecure_cookies:
    value: false
  .isolated_router.drain_timeout:
    value: 900
  .isolated_router.drain_wait:
    value: 20
  .isolated_router.enable_nontls_health_checks:
    value: true
  .isolated_router.enable_w3c:
    value: false
  .isolated_router.enable_write_access_logs:
    value: true
  .isolated_router.enable_zipkin:
    value: true
  .isolated_router.lb_healthy_threshold:
    value: 20
  .isolated_router.max_header_kb:
    value: 48
  .isolated_router.request_timeout_in_seconds:
    value: 900
  .isolated_router.static_ips:
    value: ((isolation_segment_gorouter_static_ips))
  .properties.app_graceful_shutdown_period_in_seconds:
    value: 10
  .properties.app_log_rate_limiting:
    selected_option: disable
    value: disable
  .properties.compute_isolation:
    selected_option: ((isolation_segment_compute_isolation))
    value: ((isolation_segment_compute_isolation))
  .properties.compute_isolation.enabled.isolation_segment_name:
    value: ((isolation_segment_name))
  .properties.container_networking:
    selected_option: enable
    value: enable
  .properties.enable_cpu_throttling:
    value: false
  .properties.enable_garden_containerd_mode:
    value: true
  .properties.enable_silk_policy_enforcement:
    value: false
  .properties.enable_smb_volume_driver:
    value: true
  .properties.enable_smb_volume_driver_force_nodfs:
    value: false
  .properties.enable_smb_volume_driver_force_noserverino:
    value: false
  .properties.garden_disk_cleanup:
    selected_option: reserved
    value: reserved
  .properties.garden_disk_cleanup.reserved.reserved_space_for_other_jobs_in_mb:
    value: 15360
  .properties.gorouter_customize_metrics_reporting:
    selected_option: disable
    value: disable
  .properties.gorouter_ssl_ciphers:
    value: ECDHE-RSA-AES128-GCM-SHA256:TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
  .properties.isolation_segment_domain:
    value: ((isolation_segment_domain))
  .properties.networking_poe_ssl_certs:
    value:
    - certificate:
        cert_pem: |
          -----BEGIN CERTIFICATE-----
          MIIDPzCCAiegAwIBAgIJAPn+z5f0PVV4MA0GCSqGSIb3DQEBCwUAMDUxCzAJBgNV
          BAYTAlVTMRAwDgYDVQQKDAdQaXZvdGFsMRQwEgYDVQQDDAsxNzIuMzAuNy4zMDAe
          Fw0yNDEyMDkwODM2NTRaFw0yNTEyMDkwODM2NTRaMDUxCzAJBgNVBAYTAlVTMRAw
          DgYDVQQKDAdQaXZvdGFsMRQwEgYDVQQDDAsxNzIuMzAuNy4zMDCCASIwDQYJKoZI
          hvcNAQEBBQADggEPADCCAQoCggEBAJ85RlHb++SRvkkPmyTNoA5kRPEbQQg1kuxE
          VinPb/bOgMtl+TwlFtQlc0vTmVfbZ9J0+OKGqvBheDXjHlWc2xub1mKPmBBJjL97
          m3XXwmrHjzJNsOy66Kx4PjkZ6TvHg+Z6JlbRUVWQtMXjrU6atn6bfztKbEeNdVmO
          8qcD3hXDrxbmD/P7Cs/9ARRhc4L+lSXYEn/V6BsZgLrOd+1hWN4lE1QmgNb2DdLv
          qnTUVS7FNWubs3zdDF0A6Dy9b2NcZtT/CLzqlF5e7NbraEVHaGbS2kD+jPmwCLPy
          CrJvw2GxNb5ihR6SF5/7rY2ClAM7QBcEXpARb5RtQdFDvxXeHIcCAwEAAaNSMFAw
          TgYDVR0RBEcwRYIZKi5hcHBzLjE3Mi4zMC43LjMwLm5pcC5pb4IUKi4xNzIuMzAu
          Ny4zMC5uaXAuaW+CEjE3Mi4zMC43LjMwLm5pcC5pbzANBgkqhkiG9w0BAQsFAAOC
          AQEAffBipCX0oVdSQdTRoxDO5o5yBK9KTJJScUxnEU/Ard/q+CZ4v5wZKbw/nzm+
          vfvUYMskaSMPsDjDv0/zlwA2pe9krQRvzcHtSDn+Nri8tkRUBfg0yXEhoOSjLSaJ
          GH+TPsWwRRadkI/kcT7Xtd5FmB/Do0tYs5ZrBZVOQ7QCwospWIQEOToZHu20aeY0
          z2utYafAovUyW2BwzM+avjysLi8roGSSnpi28LMWg6o2bbrJvKAZL5pTW77bdAlN
          bE8t5leY47IRAp2Y9Chcs693LNC9KHLjmJYaDBch5ekxMkQ9wz84QtnypEblx5+4
          +EzUL50ASPF8lldPa+3ZYYf93w==
          -----END CERTIFICATE-----
        private_key_pem: |
          -----BEGIN PRIVATE KEY-----
          MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCfOUZR2/vkkb5J
          D5skzaAOZETxG0EINZLsRFYpz2/2zoDLZfk8JRbUJXNL05lX22fSdPjihqrwYXg1
          4x5VnNsbm9Zij5gQSYy/e5t118Jqx48yTbDsuuiseD45Gek7x4PmeiZW0VFVkLTF
          461OmrZ+m387SmxHjXVZjvKnA94Vw68W5g/z+wrP/QEUYXOC/pUl2BJ/1egbGYC6
          znftYVjeJRNUJoDW9g3S76p01FUuxTVrm7N83QxdAOg8vW9jXGbU/wi86pReXuzW
          62hFR2hm0tpA/oz5sAiz8gqyb8NhsTW+YoUekhef+62NgpQDO0AXBF6QEW+UbUHR
          Q78V3hyHAgMBAAECggEADOaZGfzW9fgREN5g1aSLeV8KbvakWEPu+ZG34X9bNQYa
          TWCfxw3CQcIfC1/DpuiyCs1LdR8wLnXXRZZ3WLxyzFPeFPJJgdhTvRgIyo2GxRwS
          MCM3WJb0TzUW5Y2B5kQOHdh7zsD69BHbc8U0v4+thaiXsHghOdLuVSlN49ZeYiju
          BTc5qTaNzpT7zHvX3p5QWJ8c/nQL/ygUUNo9PIJc20Cv628buSHuuw6CoER34eKM
          TC43H4CGlLvTXA0hi66SCqorNVofwZS/3g/i8+/KilaN02AedrkasS4vgoREK7vf
          RHxyEwf1RryvPOn58ReC6zORVRfOe3iwF/+KgqoXcQKBgQDQVzJuZMHkewzOQRHQ
          8im6VZkidumRQNCC7+ANa/cThPPNrHoh4AiLB0qEKes7IcIFlcuvpbWqVk6XFHFh
          HuuINgLWidTYzfWrTbF9EeXwmsC8pPNZa6pAhaE2/G+yGUhQZDMZDx0omsX65EaL
          NnI6w+8DLvMDqzL1wWLV8iCJKwKBgQDDpbRDhuusfwlYpgKTscyEFcrEkcrDROyM
          Ww4icTxO6aeGcdIEH6Jnpzv3+P7iyLmbsjVKoLFDHEaDTX4FjNkdbbQUI5fZRrhx
          5pMPXg9LJcln25ail5bUH54HEeas6F8b6OdFhFGIM35/Yk5QMnCyqBqiaREiwvz+
          aMwPHrKUFQKBgGdnD7moum76/5USyJPqzPkVaOapHC2ifJqwEYS31C5U62hmNUvA
          1JykJsDHyV9U1uZMvYZU+YAsS99CHy+z1/SH0grG5+Qe/NJjwjav/m7Xb9dxCvKT
          tDFH4YbX7Vv4nmKACLhkPvWbM63dRIHtqO4vtt3enHBytN0yeSp0fN93AoGBAJzT
          ldTPMNi7mA1UPRqQ2gRCx5+b0fGGrSqwznqzVAlZaCzvzc36YZ8+wWY7VG0LQyTX
          y7n/ZzgJUUhs9IiUZ3Ecf83o3g6PjsfWcKlP12iAaJp0vaGla4Srt2upYMPXHG3t
          2nyx3P0Vcd/AOFA2rnm3IGpxWAgKTuvLq06vZ6wlAoGADsUQfKcKLobjSgoRO7AE
          TW1s2N9+HTYwA3yGA83VmfokSAWjU7W+jq8+PBwC+SEFeya7iiPIrmk2t8l/+1ai
          XOSXyyxMbzH+Xh5wYnxnx48ALw3qrvdsQ8b368WhBVBcID2NVcVtwEE3Wk0ncTYr
          lAAUti2TCd4ZyUpEGDJ1QiI=
          -----END PRIVATE KEY-----
      name: certificate
  .properties.networking_point_of_entry:
    selected_option: terminate_at_router
    value: terminate_at_router
  .properties.nfs_volume_driver:
    selected_option: enable
    value: enable
  .properties.nfs_volume_driver.enable.ldap_service_account_password:
    value: {}
  .properties.policy_enforcement_poll_interval:
    value: 5
  .properties.route_integrity:
    selected_option: tls_verify
    value: tls_verify
  .properties.route_services_internal_lookup:
    value: false
  .properties.route_services_internal_server_port:
    value: 7070
  .properties.router_backend_max_conn:
    value: 500
  .properties.router_balancing_algorithm:
    selected_option: round_robin
    value: round-robin
  .properties.router_balancing_algorithm_az_preference:
    selected_option: none
    value: none
  .properties.router_client_cert_validation:
    selected_option: request
    value: request
  .properties.router_enable_proxy:
    value: false
  .properties.router_keepalive_connections:
    selected_option: enable
    value: enable
  .properties.router_only_trust_client_ca_certs:
    selected_option: disable
    value: disable
  .properties.router_redact_query_parameters:
    selected_option: none
    value: none
  .properties.router_sticky_session_cookie_names:
    value:
    - name: JSESSIONID
  .properties.router_sticky_sessions_for_auth_negotiate:
    value: true
  .properties.routing_disable_http:
    value: false
  .properties.routing_log_client_ips:
    selected_option: log_client_ips
    value: log_client_ips
  .properties.routing_table_sharding_mode:
    selected_option: ((isolation_segment_routing_table_sharding_mode))
    value: ((isolation_segment_routing_table_sharding_mode))
  .properties.routing_tls_termination:
    selected_option: load_balancer
    value: load_balancer
  .properties.routing_tls_version_range:
    selected_option: tls_v1_2_v1_3
    value: tls_v1_2_v1_3
  .properties.smoke_tests_isolation:
    selected_option: on_demand
    value: on_demand
  .properties.system_logging:
    selected_option: disabled
    value: disabled
network-properties:
  network:
    name: ((isolation_segment_network_name))
  other_availability_zones:
    - name: ((availability_zones.0.name))
  singleton_availability_zone:
    name: ((availability_zones.0.name))
resource-config:
  isolated_diego_cell:
    max_in_flight: 4%
    additional_networks: []
    additional_vm_extensions: []
    avi:
      pools: []
    instance_type:
      id: 2xlarge.cpu
    instances: 1
    nsxt:
      lb:
        server_pools: []
      ns_groups: []
      vif_type: null
    swap_as_percent_of_memory_size: automatic
  isolated_router:
    max_in_flight: 1
    additional_networks: []
    additional_vm_extensions: []
    avi:
      pools: []
    instance_type:
      id: automatic
    instances: 1
    nsxt:
      lb:
        server_pools: []
      ns_groups: []
      vif_type: null
    swap_as_percent_of_memory_size: automatic
errand-config:
  smoke_tests_isolation:
    post-deploy-state: true

