---
opsman-configuration:
  vsphere:
    vcenter:
      datacenter: ((vcenter_datacenter))
      datastore: ((vcenter_datastore))
      folder: ((bosh_vm_folder))
      url: ((vcenter_server))
      username: ((vcenter_credentials.username))
      password: ((vcenter_credentials.password))
      resource_pool: /((vcenter_datacenter))/host/((vcenter_cluster))/Resources/sandbox
      insecure: true
    disk_type: thin
    dns: (( dns_server ))
    gateway: ((infra_network_gateway))
    hostname: opsman
    netmask: ((infra_network_netmask))
    network: ((infra_network_name))
    ntp: ((dns_server))
    private_ip: ((ops_manager_ip))
    ssh_public_key: ((ssh_public_key))