---
product-name: cf
network-properties:
  network:
    name: tas
  other_availability_zones:
    - name: ((availability_zones.0.name))
  singleton_availability_zone:
    name: ((availability_zones.0.name))
product-properties:
  .cloud_controller.apps_domain:
    value: apps.((tas_domain))
  .cloud_controller.system_domain:
    value: sys.((tas_domain))
  .mysql_monitor.recipient_email:
    value: cf-infra@pivotal.io
  .nfs_server.blobstore_internal_access_rules:
    value: ((blobstore_internal_access_rules))
  .uaa.service_provider_key_credentials:
    value:
      cert_pem: |
        ((tas_uaa_certificate))
      private_key_pem: |
        ((tas_uaa_private_key))
  .properties.container_networking_interface_plugin:
    selected_option: external
    value: external
  .properties.credhub_internal_provider_keys:
    value:
    - key:
        secret: VMware1!VMware1!VMware1!VMware1!
      name: int-encrypt
      primary: true
  .properties.isolated_routing:
    selected_option: reject_all
    value: reject_all
  .properties.networking_poe_ssl_certs:
    value: 
    - certificate:
        cert_pem: ((tas_gorouter_ssl_cert))
        private_key_pem: ((tas_gorouter_ssl_key))
      name: "gorouter"
  .properties.security_acknowledgement:
    value: X
  .properties.system_blobstore:
    value: internal
  .properties.tcp_routing:
    value: disable
  .properties.credhub_database:
    selected_option: internal_mysql
    value: internal_mysql
  .properties.nfs_volume_driver:
    selected_option: disable
    value: disable
  .properties.routing_tls_termination:
    selected_option: router
    value: router
  .properties.security_acknowledgement:
    value: x
  .router.static_ips:
    value: ((static_gorouter_ips))
resource-config:
  backup_restore:
    max_in_flight: 1
    additional_networks: []
    additional_vm_extensions: []
    instance_type:
      id: automatic
    instances: 0
    nsxt:
      lb:
        server_pools: []
      ns_groups: []
      vif_type: null
    persistent_disk:
      name: automatic
      size_mb: automatic
    swap_as_percent_of_memory_size: automatic
  blobstore:
    max_in_flight: 1
    additional_networks: []
    additional_vm_extensions: []
    instance_type:
      id: automatic
    instances: automatic
    nsxt:
      lb:
        server_pools: []
      ns_groups: []
      vif_type: null
    persistent_disk:
      name: automatic
      size_mb: automatic
    swap_as_percent_of_memory_size: automatic
  compute:
    max_in_flight: 4%
    additional_networks: []
    additional_vm_extensions: []
    instance_type:
      id: automatic
    instances: automatic
    nsxt:
      lb:
        server_pools: []
      ns_groups: []
      vif_type: null
    swap_as_percent_of_memory_size: automatic
  control:
    max_in_flight: 1
    additional_networks: []
    additional_vm_extensions: []
    instance_type:
      id: automatic
    instances: automatic
    nsxt:
      lb:
        server_pools: []
      ns_groups: []
      vif_type: null
    swap_as_percent_of_memory_size: automatic
  database:
    max_in_flight: 1
    additional_networks: []
    additional_vm_extensions: []
    instance_type:
      id: automatic
    instances: automatic
    nsxt:
      lb:
        server_pools: []
      ns_groups: []
      vif_type: null
    persistent_disk:
      name: automatic
      size_mb: automatic
    swap_as_percent_of_memory_size: automatic
  mysql_monitor:
    max_in_flight: 1
    additional_networks: []
    additional_vm_extensions: []
    instance_type:
      id: automatic
    instances: automatic
    nsxt:
      lb:
        server_pools: []
      ns_groups: []
      vif_type: null
    swap_as_percent_of_memory_size: automatic
  router:
    max_in_flight: 1
    additional_networks: []
    additional_vm_extensions: []
    instance_type:
      id: automatic
    instances: automatic
    nsxt:
      lb:
        server_pools: []
      ns_groups: []
      vif_type: null
    swap_as_percent_of_memory_size: automatic
  tcp_router:
    max_in_flight: 1
    additional_networks: []
    additional_vm_extensions: []
    instance_type:
      id: automatic
    instances: 0
    nsxt:
      lb:
        server_pools: []
      ns_groups: []
      vif_type: null
    swap_as_percent_of_memory_size: automatic
errand-config:
  deploy-autoscaler:
    post-deploy-state: true
  deploy-notifications:
    post-deploy-state: true
  deploy-notifications-ui:
    post-deploy-state: true
  metric_registrar_smoke_test:
    post-deploy-state: false
  nfsbrokerpush:
    post-deploy-state: false
  push-apps-manager:
    post-deploy-state: true
  push-offline-docs:
    post-deploy-state: false
  push-usage-service:
    post-deploy-state: true
  rotate_cc_database_key:
    post-deploy-state: false
  smbbrokerpush:
    post-deploy-state: false
  smoke_tests:
    post-deploy-state: true
  test-autoscaling:
    post-deploy-state: true