---
pivnet-product-slug: ops-manager
file-glob: "ops-manager-vsphere*.ova"
product-version: ((opsman-version))

s3-access-key-id: ((s3_access_key_id))
s3-secret-access-key: ((s3_secret_access_key))
s3-bucket: ((s3_pivnet_products_bucket))
# maybe we don't need this
# s3-endpoint: ((s3_endpoint))
# s3-disable-ssl: true
# blobstore-bucket: ((s3_pivnet_products_bucket)) # suggested in https://knowledge.broadcom.com/external/article/297504/platform-automation-task-downloadproduct.html
