---
pivnet-product-slug: ops-manager
file-glob: "ops-manager-vsphere*.ova"
product-version: ((opsman-version))

# s3-endpoint: ((s3_endpoint))
# s3-disable-ssl: true
s3-access-key-id: ((s3_access_key_id))
s3-secret-access-key: ((s3_secret_access_key))
s3-bucket: ((s3_pivnet_products_bucket))
# blobstore-bucket: ((s3_pivnet_products_bucket))
