jobs:
- name: test-job
  plan:
  - task: display-cred
    config:
      platform: linux
      platform: windows
      image_resource:
        type: registry-image
        source:
          repository: ubuntu
      run:
        path: bash
        args: [-c, "echo ((sandbox/vcenter_server))"]